global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  - "/etc/prometheus/rules/rules.yaml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alert-manager:9093"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 30s
    static_configs:
      - targets:
          - "prometheus:9090"

  - job_name: "app"
    scrape_interval: 30s
    static_configs:
      - targets:
          - "app:8000"

  - job_name: "node"
    scrape_interval: 30s
    static_configs:
      - targets:
          - "node-exporter:9100"
