global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 30s
    static_configs:
      - targets:
          - "prometheus:9090"

  - job_name: "app"
    scrape_interval: 30s
    static_configs:
      - targets:
          - "app:8000"

rule_files:
  - "etc/prometheus/rules/rule.yaml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"
